import React, { useState, useEffect, useRef } from "react";
import { Button } from "react-bootstrap";
import Navbars from "../Navbar";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faEye,
  faTrash,
  faEdit,
  faPlus,
} from "@fortawesome/free-solid-svg-icons";
import { Link } from "react-router-dom";
import Swal from "sweetalert2";
import axios from "axios";
import SideBar from "../SideBar";
import OwnerDetailModal from "../modals/OwnerDetailsModal";

function LeadList() {
  const [leads, setLeads] = useState([]);

  const fetchData = async () => {
    try {
      const url = "http://localhost:8080/api/v1/lead/";
      const response = await axios.get(url, {
        headers: {
          Authorization: localStorage.getItem("token"),
        },
      });
      if (response.status === 200) {
        setLeads(response.data.result);
      } else {
        Swal.fire({
          icon: "error",
          title: "Oops...",
          text: "Something went wrong!",
          footer: '<a href="">Why do I have this issue?</a>',
        });
      }
    } catch (error) {
      console.error(error);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);
  let style = {
    fontWeight: "bold",
    fontSize: "14px",
  };

  const ref = useRef(null);

  return (
    <>
      <div className="container-fluid">
        <div className="row">
          <div className="col-lg-2 col-md-2">
            <SideBar />
          </div>
          <div className="col-lg-10 col-md-10 mt-2">
            <Navbars />
            <div className="text">
              <h3>Leads</h3>
            </div>
            <div className="list mt-4">
              <div className="add-button">
                <Link to="/leads">
                  <Button
                    className=" btn btn-success mb-2"
                    variant="success"
                    active
                  >
                    <FontAwesomeIcon icon={faPlus} /> Add New Lead
                  </Button>
                </Link>
              </div>
              <table id="example" className="table table-striped responsive">
                <thead>
                  <tr>
                    <th>Lead Number</th>
                    <th>Owner Detail</th>
                    <th>Budget</th>
                    <th>Status</th>
                    <th>Covered Area</th>
                    <th>Assigned To</th>
                    <th>Generated By</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {leads.length !== 0 ? (
                    leads.map((lead, index) => (
                      <tr key={index}>
                        <td>{lead.lead_id}</td>
                        <td>
                          <button
                            ref={ref}
                            className="btn btn-light"
                            data-bs-toggle="modal"
                            data-bs-target="#exampleModal"
                          >
                            View Detail
                          </button>
                          <OwnerDetailModal lead={lead} title="Owner Details" />
                        </td>
                        <td>{lead.lead_budget}</td>
                        <td>
                          {lead.lead_status === 1 ? (
                            <p className="btn-success">Active</p>
                          ) : (
                            ""
                          )}
                          {lead.lead_status === 2 ? (
                            <p className="btn-info">Follow Up</p>
                          ) : (
                            ""
                          )}
                          {lead.lead_status === 0 ? (
                            <p className="btn-danger">In-Active</p>
                          ) : (
                            ""
                          )}
                        </td>
                        <td>{lead.covered_aread}SqFt</td>
                        <td>{lead.assignee_id}</td>
                        <td>{lead.generated_by}</td>
                        <td className="buttons d-flex justify-content-center">
                          <Link to={`/show/lead/${lead.id}`}>
                            <button
                              className="btn btn-primary col-3"
                              title="View"
                              active="true"
                            >
                              <FontAwesomeIcon icon={faEye} />
                            </button>
                          </Link>
                          <Link to={`/edit/lead/${lead.id}`}>
                            <button
                              className="btn btn-success col-3"
                              title="Edit"
                              active="true"
                            >
                              <FontAwesomeIcon icon={faEdit} />
                            </button>
                          </Link>
                          <button
                            // onClick={(e) => deletelead(e, user.id)}
                            className="btn btn-danger col-3"
                            active="true"
                            title="Delete"
                          >
                            <FontAwesomeIcon icon={faTrash} />
                          </button>
                        </td>
                      </tr>
                    ))
                  ) : (
                    <tr>
                      <td colSpan="6" style={{ textAlign: "center" }}>
                        No data found
                      </td>
                      <td style={{ display: "none" }}></td>
                      <td style={{ display: "none" }}></td>
                      <td style={{ display: "none" }}></td>
                      <td style={{ display: "none" }}></td>
                      <td style={{ display: "none" }}></td>
                      <td style={{ display: "none" }}></td>
                      <td style={{ display: "none" }}></td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

export default LeadList;
